### ISSUE TITLE
discrepancy of instructions between README and study.md

### ISSUE THREAD

**Issue by BenGitsCode** [ga-wdi-boston/js-javascripting-study#14] opened 2016-10-24 12:25 UTC
I didn't realize this myself until now, the readme asks for a standard pull request response, and the study.

We should clarify directions between the two to be more clear an uniform.

**Comment by jrhorn424** [comment] 2016-10-24 12:28
Possible duplicate of #2

**Closed as completed** 2016-10-24 12:40 UTC

**Comment by BenGitsCode** [comment] 2016-10-24 12:42
Definitely a duplicate of #2 just unclear on what the decision is. A lot of developers seemed confused between the study and readme though antony slacked them a link to the study.md saying to follow those instructions, which should be clear.
